### ISSUE TITLE
引发了异常: 读取访问权限冲突，this 是 0x10，不知道哪里有问题。

### ISSUE THREAD

**Issue by Molers** [Ubpa/DustEngine#2]
想参考大佬的框架和imgui写点东西，下载下来然后编译有点错误。

VS2019 Enterprise X64
运行Utopia_test_App_Editor
![image](https://user-images.githubusercontent.com/23693269/100748636-8762e280-341e-11eb-8b9d-b3d41c107d00.png)
![image](https://user-images.githubusercontent.com/23693269/100748666-9053b400-341e-11eb-9089-dea9e2ed30e5.png)

**Comment by jiexuan357** [comment]
我也是这样，请问解决了吗
