### ISSUE TITLE
编译异常：无法打开包括文件: “pthread.h”

### ISSUE THREAD

**Issue by LexTran** [Ubpa/DustEngine#7]
我下载了Utopia以后使用cmake编译，命令行报错如下：

-- export Utopia_0_0_5
-- [Dependencies]
-- - URapidJSON 0.0.3
-- - UDP 0.7.4
-- - UGM 0.6.13
-- - ULuaPP 0.2.0
-- - UECS 0.14.4
-- - UDX12 0.0.12
-- Configuring incomplete, errors occurred!
See also "G:/CS/CG/Utopia/CMakeFiles/CMakeOutput.log".
See also "G:/CS/CG/Utopia/CMakeFiles/CMakeError.log".

---------------------------------------------------------------

打开错误日志文件，显示错误如下：
  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a9903.dir\Debug\\" /Fd"cmTC_a9903.dir\Debug\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue G:\CS\CG\Utopia\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  CheckIncludeFile.c

G:\CS\CG\Utopia\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [G:\CS\CG\Utopia\CMakeFiles\CMakeTmp\cmTC_a9903.vcxproj]

----------------------------------------------------------------

我的系统是win10 64位，查了一下似乎pthread.h是Linux下的库，并不支持windows系统？但是Utopia使用DirectX接口吧，不是只能用于Windows吗？请问这是什么问题？

**Comment by Ubpa** [comment]
你没用 vs2019 吧？

**Comment by LexTran** [comment]
> 你没用 vs2019 吧？

我直接在命令行用cmake编译的，需要用vs2019吗？我没看到有解决方案，还以为直接命令行编译就行

**Comment by LexTran** [comment]
> 你没用 vs2019 吧？

我用vs2019试了一下，还是不行，编译后虽然文件路径不一样了，但是错误日志里还是报的一样的错误

-----------------------------------------------

FAILED: CMakeFiles/cmTC_23463.dir/CheckIncludeFile.c.obj 

C:\PROGRA\~2\MICROS\~4\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_23463.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_23463.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
ninja: build stopped: subcommand failed.

--------------------------------------------------

我还用NuGet工具下载了一个pthreads包，仍然报错

**Comment by King19931229** [comment]
出现一样的报错 也是VS2019的
